sonar.projectKey=LukasThome_bolao_marmiteiros
sonar.projectName=Bolão dos Marmiteiros
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/test/**,node_modules/**

sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/test/**,src/types/**,src/app/**,prisma/**

sonar.typescript.tsconfigPath=tsconfig.json
